---
# tasks file for iptables

- name: Include distribution specific variables
  include_vars: "{{ var_file }}"
  with_first_found:
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
  loop_control:
    loop_var: var_file
  tags:
    - iptables

- name: Include os family tasks
  include: "{{ task_file }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
  loop_control:
    loop_var: task_file
  tags:
    - iptables

- name: Create iptables configuration
  template:
    src: iptables.j2
    dest: "{{ iptables_configuration }}"
    backup: "{{ iptables_config_backup }}"
    owner: root
    group: root
    mode: 0600
  notify:
    - restart iptables
  tags:
    - iptables

- name: Create iptables6 configuration
  template:
    src: iptables6.j2
    dest: "{{ iptables6_configuration }}"
    owner: root
    group: root
    mode: 0600
  notify:
    - restart iptables
  tags:
    - iptables

- name: Ensure iptables is started and enabled on boot
  service:
    name: "{{ iptables_service_name }}"
    state: started
    enabled: yes
  tags:
    - iptables
