---
# tasks file for iptables (RedHat OS family specific)

- name: Install iptables packages
  yum:
    name: "{{ item }}"
    state: "{{ iptables_pkg_state }}"
  when: "{{ iptables_pkg_install }}"
  with_items:
    - "{{ iptables_packages }}"
  tags:
    - iptables
