---
# tasks file for iptables (RedHat OS family specific)

- name: Install iptables packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ iptables_packages }}"
  tags:
    - iptables
