---
# tasks file for iptables (Ubuntu specific)

- name: Install iptables packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ iptables_packages }}"
  tags:
    - iptables
